'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure
Imports System.Data.Entity.Core.Objects
Imports System.Linq

Partial Public Class GralEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=GralEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub


    Public Overridable Function spS_CatalogosOP(strCatalogo As String, condicion As String, strSel As String) As ObjectResult(Of spS_CatalogosOP_Result2)
        Dim strCatalogoParameter As ObjectParameter = If(strCatalogo IsNot Nothing, New ObjectParameter("strCatalogo", strCatalogo), New ObjectParameter("strCatalogo", GetType(String)))

        Dim condicionParameter As ObjectParameter = If(condicion IsNot Nothing, New ObjectParameter("Condicion", condicion), New ObjectParameter("Condicion", GetType(String)))

        Dim strSelParameter As ObjectParameter = If(strSel IsNot Nothing, New ObjectParameter("strSel", strSel), New ObjectParameter("strSel", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of spS_CatalogosOP_Result2)("spS_CatalogosOP", strCatalogoParameter, condicionParameter, strSelParameter)
    End Function

End Class
