'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class spS_CatalogosOP_Result2
    Public Property Clave As String
    Public Property Descripcion As String
    Public Property OcultaCampo1 As String
    Public Property OcultaCampo2 As String
    Public Property OcultaCampo3 As String

End Class
