'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure
Imports System.Data.Entity.Core.Objects
Imports System.Linq

Partial Public Class RecordEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=RecordEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub


    Public Overridable Function spD_FaseRecupera(id_Fase As Nullable(Of Integer)) As ObjectResult(Of Nullable(Of Integer))
        Dim id_FaseParameter As ObjectParameter = If(id_Fase.HasValue, New ObjectParameter("id_Fase", id_Fase), New ObjectParameter("id_Fase", GetType(Integer)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of Nullable(Of Integer))("spD_FaseRecupera", id_FaseParameter)
    End Function

    Public Overridable Function spI_FaseRecupera(strFase As String) As ObjectResult(Of Nullable(Of Integer))
        Dim strFaseParameter As ObjectParameter = If(strFase IsNot Nothing, New ObjectParameter("strFase", strFase), New ObjectParameter("strFase", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of Nullable(Of Integer))("spI_FaseRecupera", strFaseParameter)
    End Function

    Public Overridable Function spU_FaseRecupera(id_Fase As Nullable(Of Integer), strFase As String) As ObjectResult(Of Nullable(Of Integer))
        Dim id_FaseParameter As ObjectParameter = If(id_Fase.HasValue, New ObjectParameter("id_Fase", id_Fase), New ObjectParameter("id_Fase", GetType(Integer)))

        Dim strFaseParameter As ObjectParameter = If(strFase IsNot Nothing, New ObjectParameter("strFase", strFase), New ObjectParameter("strFase", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of Nullable(Of Integer))("spU_FaseRecupera", id_FaseParameter, strFaseParameter)
    End Function

    Public Overridable Function spi_Estatus_Stro(estatus As String, id_fase As Nullable(Of Integer)) As ObjectResult(Of Nullable(Of Integer))
        Dim estatusParameter As ObjectParameter = If(estatus IsNot Nothing, New ObjectParameter("estatus", estatus), New ObjectParameter("estatus", GetType(String)))

        Dim id_faseParameter As ObjectParameter = If(id_fase.HasValue, New ObjectParameter("id_fase", id_fase), New ObjectParameter("id_fase", GetType(Integer)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of Nullable(Of Integer))("spi_Estatus_Stro", estatusParameter, id_faseParameter)
    End Function

    Public Overridable Function spu_estatus_stro(id_estatus As Nullable(Of Integer), estatus As String, id_fase As Nullable(Of Integer)) As ObjectResult(Of Nullable(Of Integer))
        Dim id_estatusParameter As ObjectParameter = If(id_estatus.HasValue, New ObjectParameter("id_estatus", id_estatus), New ObjectParameter("id_estatus", GetType(Integer)))

        Dim estatusParameter As ObjectParameter = If(estatus IsNot Nothing, New ObjectParameter("estatus", estatus), New ObjectParameter("estatus", GetType(String)))

        Dim id_faseParameter As ObjectParameter = If(id_fase.HasValue, New ObjectParameter("id_fase", id_fase), New ObjectParameter("id_fase", GetType(Integer)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of Nullable(Of Integer))("spu_estatus_stro", id_estatusParameter, estatusParameter, id_faseParameter)
    End Function

    Public Overridable Function spi_Nivel_Aviso(desc_nivel As String, d_tolera As Nullable(Of Integer)) As ObjectResult(Of Nullable(Of Integer))
        Dim desc_nivelParameter As ObjectParameter = If(desc_nivel IsNot Nothing, New ObjectParameter("desc_nivel", desc_nivel), New ObjectParameter("desc_nivel", GetType(String)))

        Dim d_toleraParameter As ObjectParameter = If(d_tolera.HasValue, New ObjectParameter("d_tolera", d_tolera), New ObjectParameter("d_tolera", GetType(Integer)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of Nullable(Of Integer))("spi_Nivel_Aviso", desc_nivelParameter, d_toleraParameter)
    End Function

    Public Overridable Function spu_nivel_aviso(id_nivel As Nullable(Of Integer), desc_nivel As String, d_tolera As Nullable(Of Integer)) As ObjectResult(Of Nullable(Of Integer))
        Dim id_nivelParameter As ObjectParameter = If(id_nivel.HasValue, New ObjectParameter("id_nivel", id_nivel), New ObjectParameter("id_nivel", GetType(Integer)))

        Dim desc_nivelParameter As ObjectParameter = If(desc_nivel IsNot Nothing, New ObjectParameter("desc_nivel", desc_nivel), New ObjectParameter("desc_nivel", GetType(String)))

        Dim d_toleraParameter As ObjectParameter = If(d_tolera.HasValue, New ObjectParameter("d_tolera", d_tolera), New ObjectParameter("d_tolera", GetType(Integer)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of Nullable(Of Integer))("spu_nivel_aviso", id_nivelParameter, desc_nivelParameter, d_toleraParameter)
    End Function

    Public Overridable Function spi_taviso_Usuario(cod_usuario As String, cod_sector As Nullable(Of Decimal), id_nivel As Nullable(Of Integer)) As ObjectResult(Of Nullable(Of Integer))
        Dim cod_usuarioParameter As ObjectParameter = If(cod_usuario IsNot Nothing, New ObjectParameter("cod_usuario", cod_usuario), New ObjectParameter("cod_usuario", GetType(String)))

        Dim cod_sectorParameter As ObjectParameter = If(cod_sector.HasValue, New ObjectParameter("cod_sector", cod_sector), New ObjectParameter("cod_sector", GetType(Decimal)))

        Dim id_nivelParameter As ObjectParameter = If(id_nivel.HasValue, New ObjectParameter("id_nivel", id_nivel), New ObjectParameter("id_nivel", GetType(Integer)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of Nullable(Of Integer))("spi_taviso_Usuario", cod_usuarioParameter, cod_sectorParameter, id_nivelParameter)
    End Function

    Public Overridable Function spu_taviso_Usuario(cod_usuario As String, cod_sector As Nullable(Of Decimal), idav As Nullable(Of Integer), nivel As Nullable(Of Integer)) As ObjectResult(Of Nullable(Of Integer))
        Dim cod_usuarioParameter As ObjectParameter = If(cod_usuario IsNot Nothing, New ObjectParameter("cod_usuario", cod_usuario), New ObjectParameter("cod_usuario", GetType(String)))

        Dim cod_sectorParameter As ObjectParameter = If(cod_sector.HasValue, New ObjectParameter("cod_sector", cod_sector), New ObjectParameter("cod_sector", GetType(Decimal)))

        Dim idavParameter As ObjectParameter = If(idav.HasValue, New ObjectParameter("idav", idav), New ObjectParameter("idav", GetType(Integer)))

        Dim nivelParameter As ObjectParameter = If(nivel.HasValue, New ObjectParameter("nivel", nivel), New ObjectParameter("nivel", GetType(Integer)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of Nullable(Of Integer))("spu_taviso_Usuario", cod_usuarioParameter, cod_sectorParameter, idavParameter, nivelParameter)
    End Function

    Public Overridable Function spU_ActivaJob(hora As String, activo As Nullable(Of Boolean)) As ObjectResult(Of Nullable(Of Integer))
        Dim horaParameter As ObjectParameter = If(hora IsNot Nothing, New ObjectParameter("Hora", hora), New ObjectParameter("Hora", GetType(String)))

        Dim activoParameter As ObjectParameter = If(activo.HasValue, New ObjectParameter("Activo", activo), New ObjectParameter("Activo", GetType(Boolean)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of Nullable(Of Integer))("spU_ActivaJob", horaParameter, activoParameter)
    End Function

    Public Overridable Function ModJob(hora As String, fecha As String, habilita As Nullable(Of Boolean)) As ObjectResult(Of Nullable(Of Integer))
        Dim horaParameter As ObjectParameter = If(hora IsNot Nothing, New ObjectParameter("hora", hora), New ObjectParameter("hora", GetType(String)))

        Dim fechaParameter As ObjectParameter = If(fecha IsNot Nothing, New ObjectParameter("fecha", fecha), New ObjectParameter("fecha", GetType(String)))

        Dim habilitaParameter As ObjectParameter = If(habilita.HasValue, New ObjectParameter("habilita", habilita), New ObjectParameter("habilita", GetType(Boolean)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of Nullable(Of Integer))("ModJob", horaParameter, fechaParameter, habilitaParameter)
    End Function

    Public Overridable Function spD_Estatus_Stro(id_estatus As Nullable(Of Integer)) As ObjectResult(Of Nullable(Of Integer))
        Dim id_estatusParameter As ObjectParameter = If(id_estatus.HasValue, New ObjectParameter("id_estatus", id_estatus), New ObjectParameter("id_estatus", GetType(Integer)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of Nullable(Of Integer))("spD_Estatus_Stro", id_estatusParameter)
    End Function

    Public Overridable Function spD_Nivel_Aviso(id_nivel As Nullable(Of Integer)) As ObjectResult(Of Nullable(Of Integer))
        Dim id_nivelParameter As ObjectParameter = If(id_nivel.HasValue, New ObjectParameter("id_nivel", id_nivel), New ObjectParameter("id_nivel", GetType(Integer)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of Nullable(Of Integer))("spD_Nivel_Aviso", id_nivelParameter)
    End Function

    Public Overridable Function spD_tAviso_Usuario(idav As Nullable(Of Integer)) As ObjectResult(Of Nullable(Of Integer))
        Dim idavParameter As ObjectParameter = If(idav.HasValue, New ObjectParameter("idav", idav), New ObjectParameter("idav", GetType(Integer)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of Nullable(Of Integer))("spD_tAviso_Usuario", idavParameter)
    End Function

    Public Overridable Function sp_rptMovSinxReas(tipo_mov As Nullable(Of Integer), nro_stro As String, broker As String, aseg As String, reaseg As String, cod_ramo_conta As String, poliza As String, fec_desde As String, fec_hasta As String) As ObjectResult(Of sp_rptMovSinxReas_Result)
        Dim tipo_movParameter As ObjectParameter = If(tipo_mov.HasValue, New ObjectParameter("tipo_mov", tipo_mov), New ObjectParameter("tipo_mov", GetType(Integer)))

        Dim nro_stroParameter As ObjectParameter = If(nro_stro IsNot Nothing, New ObjectParameter("nro_stro", nro_stro), New ObjectParameter("nro_stro", GetType(String)))

        Dim brokerParameter As ObjectParameter = If(broker IsNot Nothing, New ObjectParameter("broker", broker), New ObjectParameter("broker", GetType(String)))

        Dim asegParameter As ObjectParameter = If(aseg IsNot Nothing, New ObjectParameter("aseg", aseg), New ObjectParameter("aseg", GetType(String)))

        Dim reasegParameter As ObjectParameter = If(reaseg IsNot Nothing, New ObjectParameter("reaseg", reaseg), New ObjectParameter("reaseg", GetType(String)))

        Dim cod_ramo_contaParameter As ObjectParameter = If(cod_ramo_conta IsNot Nothing, New ObjectParameter("cod_ramo_conta", cod_ramo_conta), New ObjectParameter("cod_ramo_conta", GetType(String)))

        Dim polizaParameter As ObjectParameter = If(poliza IsNot Nothing, New ObjectParameter("poliza", poliza), New ObjectParameter("poliza", GetType(String)))

        Dim fec_desdeParameter As ObjectParameter = If(fec_desde IsNot Nothing, New ObjectParameter("fec_desde", fec_desde), New ObjectParameter("fec_desde", GetType(String)))

        Dim fec_hastaParameter As ObjectParameter = If(fec_hasta IsNot Nothing, New ObjectParameter("fec_hasta", fec_hasta), New ObjectParameter("fec_hasta", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of sp_rptMovSinxReas_Result)("sp_rptMovSinxReas", tipo_movParameter, nro_stroParameter, brokerParameter, asegParameter, reasegParameter, cod_ramo_contaParameter, polizaParameter, fec_desdeParameter, fec_hastaParameter)
    End Function

    Public Overridable Function spI_PolNoAC(id_pv As Nullable(Of Integer), cod_usuario As String, cod_submodweb As Nullable(Of Integer)) As ObjectResult(Of Nullable(Of Integer))
        Dim id_pvParameter As ObjectParameter = If(id_pv.HasValue, New ObjectParameter("id_pv", id_pv), New ObjectParameter("id_pv", GetType(Integer)))

        Dim cod_usuarioParameter As ObjectParameter = If(cod_usuario IsNot Nothing, New ObjectParameter("cod_usuario", cod_usuario), New ObjectParameter("cod_usuario", GetType(String)))

        Dim cod_submodwebParameter As ObjectParameter = If(cod_submodweb.HasValue, New ObjectParameter("cod_submodweb", cod_submodweb), New ObjectParameter("cod_submodweb", GetType(Integer)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of Nullable(Of Integer))("spI_PolNoAC", id_pvParameter, cod_usuarioParameter, cod_submodwebParameter)
    End Function

    Public Overridable Function spD_PolNoAC(id_pv As String, cod_submod_web As Nullable(Of Integer)) As ObjectResult(Of Nullable(Of Integer))
        Dim id_pvParameter As ObjectParameter = If(id_pv IsNot Nothing, New ObjectParameter("id_pv", id_pv), New ObjectParameter("id_pv", GetType(String)))

        Dim cod_submod_webParameter As ObjectParameter = If(cod_submod_web.HasValue, New ObjectParameter("cod_submod_web", cod_submod_web), New ObjectParameter("cod_submod_web", GetType(Integer)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of Nullable(Of Integer))("spD_PolNoAC", id_pvParameter, cod_submod_webParameter)
    End Function

    Public Overridable Function sp_RepartoReaFac(id_pv As Nullable(Of Integer), no_stro As Nullable(Of Integer)) As ObjectResult(Of sp_RepartoReaFac_Result)
        Dim id_pvParameter As ObjectParameter = If(id_pv.HasValue, New ObjectParameter("id_pv", id_pv), New ObjectParameter("id_pv", GetType(Integer)))

        Dim no_stroParameter As ObjectParameter = If(no_stro.HasValue, New ObjectParameter("no_stro", no_stro), New ObjectParameter("no_stro", GetType(Integer)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of sp_RepartoReaFac_Result)("sp_RepartoReaFac", id_pvParameter, no_stroParameter)
    End Function

    Public Overridable Function spI_AjustesSin(sINIESTRO As Nullable(Of Integer), consecutivo As Nullable(Of Integer), rEASEGURADOR_ANT As String, rEASEGURADOR As String, cORREDOR_ANT As String, cORREDOR As String, rEG_REA_ANT As String, rEG_REASEGURADOR As String, fEC_INI_VIG_ANT As String, fEC_INI_VIG As String, fEC_FIN_VIG_ANT As String, fEC_FIN_VIG As String, cAUSA_STRO_ANT As String, cAUSA_STRO As String, dIR_STRO_ANT As String, dIR_STRO As String, aJUSTADOR_ANT As String, aJUSTADOR As String, fecha_Ajuste As String, usuario As String) As ObjectResult(Of Nullable(Of Integer))
        Dim sINIESTROParameter As ObjectParameter = If(sINIESTRO.HasValue, New ObjectParameter("SINIESTRO", sINIESTRO), New ObjectParameter("SINIESTRO", GetType(Integer)))

        Dim consecutivoParameter As ObjectParameter = If(consecutivo.HasValue, New ObjectParameter("Consecutivo", consecutivo), New ObjectParameter("Consecutivo", GetType(Integer)))

        Dim rEASEGURADOR_ANTParameter As ObjectParameter = If(rEASEGURADOR_ANT IsNot Nothing, New ObjectParameter("REASEGURADOR_ANT", rEASEGURADOR_ANT), New ObjectParameter("REASEGURADOR_ANT", GetType(String)))

        Dim rEASEGURADORParameter As ObjectParameter = If(rEASEGURADOR IsNot Nothing, New ObjectParameter("REASEGURADOR", rEASEGURADOR), New ObjectParameter("REASEGURADOR", GetType(String)))

        Dim cORREDOR_ANTParameter As ObjectParameter = If(cORREDOR_ANT IsNot Nothing, New ObjectParameter("CORREDOR_ANT", cORREDOR_ANT), New ObjectParameter("CORREDOR_ANT", GetType(String)))

        Dim cORREDORParameter As ObjectParameter = If(cORREDOR IsNot Nothing, New ObjectParameter("CORREDOR", cORREDOR), New ObjectParameter("CORREDOR", GetType(String)))

        Dim rEG_REA_ANTParameter As ObjectParameter = If(rEG_REA_ANT IsNot Nothing, New ObjectParameter("REG_REA_ANT", rEG_REA_ANT), New ObjectParameter("REG_REA_ANT", GetType(String)))

        Dim rEG_REASEGURADORParameter As ObjectParameter = If(rEG_REASEGURADOR IsNot Nothing, New ObjectParameter("REG_REASEGURADOR", rEG_REASEGURADOR), New ObjectParameter("REG_REASEGURADOR", GetType(String)))

        Dim fEC_INI_VIG_ANTParameter As ObjectParameter = If(fEC_INI_VIG_ANT IsNot Nothing, New ObjectParameter("FEC_INI_VIG_ANT", fEC_INI_VIG_ANT), New ObjectParameter("FEC_INI_VIG_ANT", GetType(String)))

        Dim fEC_INI_VIGParameter As ObjectParameter = If(fEC_INI_VIG IsNot Nothing, New ObjectParameter("FEC_INI_VIG", fEC_INI_VIG), New ObjectParameter("FEC_INI_VIG", GetType(String)))

        Dim fEC_FIN_VIG_ANTParameter As ObjectParameter = If(fEC_FIN_VIG_ANT IsNot Nothing, New ObjectParameter("FEC_FIN_VIG_ANT", fEC_FIN_VIG_ANT), New ObjectParameter("FEC_FIN_VIG_ANT", GetType(String)))

        Dim fEC_FIN_VIGParameter As ObjectParameter = If(fEC_FIN_VIG IsNot Nothing, New ObjectParameter("FEC_FIN_VIG", fEC_FIN_VIG), New ObjectParameter("FEC_FIN_VIG", GetType(String)))

        Dim cAUSA_STRO_ANTParameter As ObjectParameter = If(cAUSA_STRO_ANT IsNot Nothing, New ObjectParameter("CAUSA_STRO_ANT", cAUSA_STRO_ANT), New ObjectParameter("CAUSA_STRO_ANT", GetType(String)))

        Dim cAUSA_STROParameter As ObjectParameter = If(cAUSA_STRO IsNot Nothing, New ObjectParameter("CAUSA_STRO", cAUSA_STRO), New ObjectParameter("CAUSA_STRO", GetType(String)))

        Dim dIR_STRO_ANTParameter As ObjectParameter = If(dIR_STRO_ANT IsNot Nothing, New ObjectParameter("DIR_STRO_ANT", dIR_STRO_ANT), New ObjectParameter("DIR_STRO_ANT", GetType(String)))

        Dim dIR_STROParameter As ObjectParameter = If(dIR_STRO IsNot Nothing, New ObjectParameter("DIR_STRO", dIR_STRO), New ObjectParameter("DIR_STRO", GetType(String)))

        Dim aJUSTADOR_ANTParameter As ObjectParameter = If(aJUSTADOR_ANT IsNot Nothing, New ObjectParameter("AJUSTADOR_ANT", aJUSTADOR_ANT), New ObjectParameter("AJUSTADOR_ANT", GetType(String)))

        Dim aJUSTADORParameter As ObjectParameter = If(aJUSTADOR IsNot Nothing, New ObjectParameter("AJUSTADOR", aJUSTADOR), New ObjectParameter("AJUSTADOR", GetType(String)))

        Dim fecha_AjusteParameter As ObjectParameter = If(fecha_Ajuste IsNot Nothing, New ObjectParameter("Fecha_Ajuste", fecha_Ajuste), New ObjectParameter("Fecha_Ajuste", GetType(String)))

        Dim usuarioParameter As ObjectParameter = If(usuario IsNot Nothing, New ObjectParameter("Usuario", usuario), New ObjectParameter("Usuario", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of Nullable(Of Integer))("spI_AjustesSin", sINIESTROParameter, consecutivoParameter, rEASEGURADOR_ANTParameter, rEASEGURADORParameter, cORREDOR_ANTParameter, cORREDORParameter, rEG_REA_ANTParameter, rEG_REASEGURADORParameter, fEC_INI_VIG_ANTParameter, fEC_INI_VIGParameter, fEC_FIN_VIG_ANTParameter, fEC_FIN_VIGParameter, cAUSA_STRO_ANTParameter, cAUSA_STROParameter, dIR_STRO_ANTParameter, dIR_STROParameter, aJUSTADOR_ANTParameter, aJUSTADORParameter, fecha_AjusteParameter, usuarioParameter)
    End Function

End Class
