'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure
Imports System.Data.Entity.Core.Objects
Imports System.Linq

Partial Public Class UATEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=UATEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub


    Public Overridable Function spS_AjusteHistBdx(fec_desde As String, fec_hasta As String) As ObjectResult(Of spS_AjusteHistBdx_Result2)
        Dim fec_desdeParameter As ObjectParameter = If(fec_desde IsNot Nothing, New ObjectParameter("fec_desde", fec_desde), New ObjectParameter("fec_desde", GetType(String)))

        Dim fec_hastaParameter As ObjectParameter = If(fec_hasta IsNot Nothing, New ObjectParameter("fec_hasta", fec_hasta), New ObjectParameter("fec_hasta", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of spS_AjusteHistBdx_Result2)("spS_AjusteHistBdx", fec_desdeParameter, fec_hastaParameter)
    End Function

End Class
