'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class spS_AjusteHistBdx_Result2
    Public Property SINIESTRO As Integer
    Public Property SUBSINIESTRO As Integer
    Public Property SUCURSAL As String
    Public Property RAMO As String
    Public Property POLIZA As Decimal
    Public Property SUFIJO As Integer
    Public Property ENDOSO As Decimal
    Public Property MONEDA As String
    Public Property FECHA_DISTRIBUCION As String
    Public Property SOLICITUD As String
    Public Property MONTO_MOVIMIENTO As Nullable(Of Decimal)
    Public Property AJUSTE As String

End Class
