'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure
Imports System.Data.Entity.Core.Objects
Imports System.Linq

Partial Public Class ReportEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=ReportEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub


    Public Overridable Function spI_VersionReporte(cod_modulo As Nullable(Of Integer), cod_submodulo_web As Nullable(Of Integer), cod_reporte As Nullable(Of Integer), cod_usuario As String, descripcion As String, filtros As String, formato As String, sn_Temporal As Nullable(Of Integer)) As ObjectResult(Of Nullable(Of Integer))
        Dim cod_moduloParameter As ObjectParameter = If(cod_modulo.HasValue, New ObjectParameter("cod_modulo", cod_modulo), New ObjectParameter("cod_modulo", GetType(Integer)))

        Dim cod_submodulo_webParameter As ObjectParameter = If(cod_submodulo_web.HasValue, New ObjectParameter("cod_submodulo_web", cod_submodulo_web), New ObjectParameter("cod_submodulo_web", GetType(Integer)))

        Dim cod_reporteParameter As ObjectParameter = If(cod_reporte.HasValue, New ObjectParameter("cod_reporte", cod_reporte), New ObjectParameter("cod_reporte", GetType(Integer)))

        Dim cod_usuarioParameter As ObjectParameter = If(cod_usuario IsNot Nothing, New ObjectParameter("cod_usuario", cod_usuario), New ObjectParameter("cod_usuario", GetType(String)))

        Dim descripcionParameter As ObjectParameter = If(descripcion IsNot Nothing, New ObjectParameter("descripcion", descripcion), New ObjectParameter("descripcion", GetType(String)))

        Dim filtrosParameter As ObjectParameter = If(filtros IsNot Nothing, New ObjectParameter("filtros", filtros), New ObjectParameter("filtros", GetType(String)))

        Dim formatoParameter As ObjectParameter = If(formato IsNot Nothing, New ObjectParameter("formato", formato), New ObjectParameter("formato", GetType(String)))

        Dim sn_TemporalParameter As ObjectParameter = If(sn_Temporal.HasValue, New ObjectParameter("sn_Temporal", sn_Temporal), New ObjectParameter("sn_Temporal", GetType(Integer)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of Nullable(Of Integer))("spI_VersionReporte", cod_moduloParameter, cod_submodulo_webParameter, cod_reporteParameter, cod_usuarioParameter, descripcionParameter, filtrosParameter, formatoParameter, sn_TemporalParameter)
    End Function

End Class
