'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure
Imports System.Data.Entity.Core.Objects
Imports System.Linq

Partial Public Class OPEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=OPEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub


    Public Overridable Function spI_PolNoPago(id_pv As Nullable(Of Integer), cod_usuario As String) As ObjectResult(Of spI_PolNoPago_Result)
        Dim id_pvParameter As ObjectParameter = If(id_pv.HasValue, New ObjectParameter("id_pv", id_pv), New ObjectParameter("id_pv", GetType(Integer)))

        Dim cod_usuarioParameter As ObjectParameter = If(cod_usuario IsNot Nothing, New ObjectParameter("cod_usuario", cod_usuario), New ObjectParameter("cod_usuario", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of spI_PolNoPago_Result)("spI_PolNoPago", id_pvParameter, cod_usuarioParameter)
    End Function

    Public Overridable Function spD_PolNoPago(id_pv As String) As ObjectResult(Of spD_PolNoPago_Result)
        Dim id_pvParameter As ObjectParameter = If(id_pv IsNot Nothing, New ObjectParameter("id_pv", id_pv), New ObjectParameter("id_pv", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of spD_PolNoPago_Result)("spD_PolNoPago", id_pvParameter)
    End Function

End Class
